<?php /** @var \Training\LayoutExample\Block\Layout\Index $block */?>
<h2><?= $block->getSubTitle()?></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab commodi consectetur culpa dignissimos dolor eos, eum facere fuga, itaque nihil non officia officiis quae quas quisquam quo quos ratione ut.</p>

<?= $block->getChildHtml('layout_note') ?>

<?= $block->getNodeHtml() ?>

<?= $block->getChildHtml('cms_block_example') ?>
